import { CompanyInfo, Proforma } from '../types/proforma';

export const DEFAULT_COMPANY: CompanyInfo = {
  name: 'Smart Living Elite Solutions',
  tagline: 'Domotique, Infrastructure & Services Numériques',
  contactPerson: 'Domotique Elite',
  email: 'contact@domoelite.com',
  phone: '+509 3700-1234',
  address: 'Delmas 75',
  city: 'Cassagnol 13, Haïti',
  taxId: 'NIF: 004-982-123-0',
  bankDetails: 'Unibank / Sogebank / MonCash - Compte USD: 230-1029-8812903',
  currency: 'USD',
  defaultTerms: 'ANNUAL FEE: THE TOTAL AMOUNT OF USD 160.00 MUST BE PAID EVERY YEAR TO KEEP THE SERVICES ACTIVE.',
  logoUrl: '',
  defaultTemplate: 'wave',
};

export const INITIAL_PROFORMAS: Proforma[] = [
  {
    id: 'pf-demo-image',
    enterpriseId: 'ent-1',
    proformaNumber: 'Devis # S01966',
    title: 'Configuration Nom de Domaine, Sécurité & Messagerie Professionnelle',
    issueDate: '2026-09-16',
    validityDate: '2026-10-16',
    status: 'en_attente',
    template: 'wave',
    client: {
      name: 'Fritz Junior Joseph',
      company: 'MSI SA',
      email: 'f.joseph@msi-haiti.com',
      phone: '+509 3812-4455',
      address: 'Pétion-Ville',
      city: 'Haïti',
      taxId: 'NIF: 001-345-789-1',
    },
    items: [
      {
        id: 'it-img-1',
        designation: 'DOMAIN NAME',
        description: 'CONFIGURATION: DOMAIN REGISTRATION/SETUP, DNS CONFIGURATION, AND CONNECTION TO THE CLIENT\'S WEBSITE AND/OR PROFESSIONAL EMAIL SERVICES.',
        quantity: 1,
        unitPrice: 55,
        discountPercent: 0,
        taxRate: 0,
        totalHT: 55,
        totalTTC: 55,
      },
      {
        id: 'it-img-2',
        designation: 'INITIAL SETUP SECURITY',
        description: 'SSL CERTIFICATE, BASIC PROTECTION, INITIAL BACKUP, INITIAL SEARCH ENGINE OPTIMIZATION',
        quantity: 1,
        unitPrice: 40,
        discountPercent: 0,
        taxRate: 0,
        totalHT: 40,
        totalTTC: 40,
      },
      {
        id: 'it-img-3',
        designation: 'DNS CONFIGURATION',
        description: 'MX, SPF, DKIM, DMARC, AND VERIFICATION',
        quantity: 1,
        unitPrice: 40,
        discountPercent: 0,
        taxRate: 0,
        totalHT: 40,
        totalTTC: 40,
      },
      {
        id: 'it-img-4',
        designation: 'PROFESSIONAL EMAIL ACCOUNT SETUP',
        description: 'CREATION AND CONFIGURATION OF A PROFESSIONAL EMAIL ACCOUNT USING THE CLIENT\'S DOMAIN NAME, INCLUDING MAILBOX SETUP, DNS CONFIGURATION, EMAIL AUTHENTICATION',
        quantity: 1,
        unitPrice: 25,
        discountPercent: 0,
        taxRate: 0,
        totalHT: 25,
        totalTTC: 25,
      },
    ],
    subtotalHT: 160,
    totalDiscount: 0,
    totalTax: 0,
    totalTTC: 160,
    paidAmount: 0,
    currency: 'USD',
    paymentTerms: 'ANNUAL FEE: THE TOTAL AMOUNT OF USD 160.00 MUST BE PAID EVERY YEAR TO KEEP THE SERVICES ACTIVE.',
    notes: 'Devis soumis au client. En attente de validation pour activation des services.',
    statusHistory: [
      { id: 'sh-1', status: 'brouillon', date: '2026-09-16 09:00', note: 'Création du devis pour Fritz Junior Joseph, MSI SA' },
      { id: 'sh-2', status: 'en_attente', date: '2026-09-16 10:15', note: 'Devis transmis par email (Contact: Domotique Elite)' },
    ],
    createdAt: '2026-09-16T09:00:00.000Z',
    updatedAt: '2026-09-16T10:15:00.000Z',
  },
  {
    id: 'pf-1',
    enterpriseId: 'ent-1',
    proformaNumber: 'Devis # S01967',
    title: 'Installation Système Domotique & Caméras IP Haute Définition',
    issueDate: '2026-09-18',
    validityDate: '2026-10-18',
    status: 'encaisse',
    template: 'wave',
    client: {
      name: 'Jean-Claude Pierre',
      company: 'Résidence Prestige',
      email: 'jc.pierre@gmail.com',
      phone: '+509 3445-9012',
      address: 'Route de Kenscoff',
      city: 'Haïti',
    },
    items: [
      {
        id: 'it-1',
        designation: 'CENTRALE DOMOTIQUE INTELLIGENTE',
        description: 'HUB CENTRAL SANS FIL Z-WAVE/ZIGBEE AVEC CONTRÔLE SUR APPLICATION MOBILE',
        quantity: 1,
        unitPrice: 450,
        discountPercent: 0,
        taxRate: 0,
        totalHT: 450,
        totalTTC: 450,
      },
      {
        id: 'it-2',
        designation: 'CAMÉRAS DE SURVEILLANCE EXTÉRIEURE 4K',
        description: 'VISION NOCTURNE COULEUR, DÉTECTION IA VÉHICULES ET HUMAINS, ENREGISTREUR NVR 4TO',
        quantity: 4,
        unitPrice: 220,
        discountPercent: 0,
        taxRate: 0,
        totalHT: 880,
        totalTTC: 880,
      },
      {
        id: 'it-3',
        designation: 'CÂBLAGE & CONFIGURATION SUR SITE',
        description: 'INSTALLATION COMPLÈTE, TEST DE CONNECTIVITÉ ET FORMATION UTILISATEUR',
        quantity: 1,
        unitPrice: 270,
        discountPercent: 0,
        taxRate: 0,
        totalHT: 270,
        totalTTC: 270,
      },
    ],
    subtotalHT: 1600,
    totalDiscount: 0,
    totalTax: 0,
    totalTTC: 1600,
    paidAmount: 1600,
    currency: 'USD',
    paymentTerms: 'Paiement 100% reçu par virement bancaire.',
    notes: 'Installation terminée et validée par le client.',
    statusHistory: [
      { id: 'sh-3', status: 'en_attente', date: '2026-09-18 11:00', note: 'Envoi du devis' },
      { id: 'sh-4', status: 'valide', date: '2026-09-20 14:00', note: 'Accord signé reçu' },
      { id: 'sh-5', status: 'encaisse', date: '2026-09-21 16:30', note: 'Paiement de $ 1,600.00 perçu', amountCollected: 1600 },
    ],
    createdAt: '2026-09-18T11:00:00.000Z',
    updatedAt: '2026-09-21T16:30:00.000Z',
  },
  {
    id: 'pf-2',
    enterpriseId: 'ent-2',
    proformaNumber: 'Devis # S01968',
    title: 'Développement de Portail Web & Intégration Paiement MonCash',
    issueDate: '2026-09-21',
    validityDate: '2026-10-21',
    status: 'valide',
    template: 'corporate',
    client: {
      name: 'Nathalie Cadet',
      company: 'Caraïbes Distribution Express',
      email: 'ncadet@caraibes-express.ht',
      phone: '+509 3100-7890',
      address: 'Boulevard Toussaint Louverture',
      city: 'Port-au-Prince',
    },
    items: [
      {
        id: 'it-4',
        designation: 'CONCEPTION UI/UX & DÉVELOPPEMENT WEB',
        description: 'SITE VITRINE ET PORTAIL E-COMMERCE ADAPTÉ MOBILE ET TABLETTE',
        quantity: 1,
        unitPrice: 1200,
        discountPercent: 0,
        taxRate: 0,
        totalHT: 1200,
        totalTTC: 1200,
      },
      {
        id: 'it-5',
        designation: 'INTÉGRATION PASSERELLE PAIEMENT',
        description: 'MONCASH API + CARTE BANCAIRE STRIPE SÉCURISÉ',
        quantity: 1,
        unitPrice: 450,
        discountPercent: 0,
        taxRate: 0,
        totalHT: 450,
        totalTTC: 450,
      },
    ],
    subtotalHT: 1650,
    totalDiscount: 0,
    totalTax: 0,
    totalTTC: 1650,
    paidAmount: 825, // Acompte 50%
    currency: 'USD',
    paymentTerms: '50% d\'acompte à la commande ($ 825.00 reçu), 50% à la mise en ligne.',
    notes: 'Acompte reçu. Projet en phase de production.',
    statusHistory: [
      { id: 'sh-6', status: 'en_attente', date: '2026-09-21 15:00', note: 'Proposition commerciale' },
      { id: 'sh-7', status: 'valide', date: '2026-09-22 10:00', note: 'Devis accepté et signé' },
      { id: 'sh-8', status: 'valide', date: '2026-09-22 12:00', note: 'Acompte de $ 825.00 perçu', amountCollected: 825 },
    ],
    createdAt: '2026-09-21T15:00:00.000Z',
    updatedAt: '2026-09-22T12:00:00.000Z',
  },
];
